spring:
  application:
    name: financial-unit
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: 'jdbc:postgresql://localhost:5432/database'
    username: 'user'
    password: 'password'
    hikari:
      maximum-pool-size: 10

  flyway:
    url: 'jdbc:postgresql://localhost:5432/database'
    user: 'user'
    password: 'password'


server:
  port: 8080

