spring:
  application:
    name: financial-unit
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: ${MAX_POOL_SIZE}


  flyway:
    url: ${SPRING_DATASOURCE_URL}
    user: ${FLYWAY_DATASOURCE_USER}
    password: ${FLYWAY_DATASOURCE_PASSWORD}

springdoc:
  override-with-generic-response: false

server:
  port: ${SERVER_PORT}

